default: &default
  adapter: postgresql
  encoding: unicode
  locale: pt_BR
  pool: 5

development:
  <<: *default
  database: luw_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: luw_test
  username: postgres
  password: postgres

